FROM debian:12-slim

ARG CONTAINER_GID=10000
ARG CONTAINER_UID=10000
ARG WINE_BRANCH=stable

ENV DEBIAN_FRONTEND="noninteractive"
ENV STEAM_APP_ID="4129620"
ENV HOME="/home/steam"
ENV WINDROSE_PATH="/home/steam/windrose"
ENV STEAMCMD_PATH="/home/steam/steamcmd"
ENV WINEPREFIX="/home/steam/.wine"
ENV WINEARCH="win64"

RUN groupadd -g $CONTAINER_GID steam \
    && useradd -g $CONTAINER_GID -u $CONTAINER_UID -m steam \
    && dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        ca-certificates \
        curl \
        gnupg \
    && install -dm755 /etc/apt/keyrings \
    && curl -fsSL -o /etc/apt/keyrings/winehq-archive.key \
        https://dl.winehq.org/wine-builds/winehq.key \
    && curl -fsSL -o /etc/apt/sources.list.d/winehq-bookworm.sources \
        https://dl.winehq.org/wine-builds/debian/dists/bookworm/winehq-bookworm.sources \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
        dbus \
        xvfb \
        xauth \
        winehq-${WINE_BRANCH} \
        jq \
        locales \
        lib32gcc-s1 \
        procps \
    && echo 'LANG="en_US.UTF-8"' > /etc/default/locale \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen \
    && rm -f /etc/machine-id \
    && dbus-uuidgen --ensure=/etc/machine-id \
    && install -dm1777 /tmp/.X11-unix \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && apt-get autoremove -y

USER steam

RUN mkdir "$WINDROSE_PATH" \
    && mkdir -p "${STEAMCMD_PATH}" \
    && curl -sqL https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz | tar zxvf - -C ${STEAMCMD_PATH} \
    && chmod +x ${STEAMCMD_PATH}/steamcmd.sh \
    && ${STEAMCMD_PATH}/steamcmd.sh +login anonymous +quit \
    && mkdir -p "${WINEPREFIX}" \
    && WINEDLLOVERRIDES="mscoree,mshtml=" WINEDEBUG=-all wineboot --init \
    && wineserver -w
    
COPY entrypoint.sh /home/steam/entrypoint.sh

WORKDIR /home/steam

CMD ["/home/steam/entrypoint.sh"]
