{{- $pw := .Values.windrose.server.password }}
{{- if and $pw.value (not $pw.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "windrose-server.passwordSecretName" . }}
  labels:
    {{- include "windrose-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ $pw.secretKey | default "password" }}: {{ $pw.value | quote }}
{{- end }}
