apiVersion: v2
name: windrose-server
description: Windrose Dedicated Server running under Wine in a Linux container
type: application
version: 0.2.0
appVersion: "0.10.0"
kubeVersion: ">=1.24.0-0"
home: https://github.com/sknnr/windrose-server
sources:
  - https://github.com/sknnr/windrose-server
keywords:
  - game-server
  - windrose
  - wine
  - steamcmd
maintainers:
  - name: John Skinner
    email: john@sknnr.io
